config/routes.rb
Rails.application.routes.draw do
  mount API::Base, at: "/"
  devise_for :users
  resources :access_points
  resources :file_to_updates
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/access_group.rb
class AccessGroup < ApplicationRecord
end

app/models/access_group_service.rb
class AccessGroupService < ApplicationRecord
  belongs_to :access_group
  belongs_to :service
end

app/models/access_point.rb
class AccessPoint < ApplicationRecord
  has_and_belongs_to_many :devices
  has_and_belongs_to_many :file_packages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus.rb
class Bus < ApplicationRecord
end

app/models/bus_event.rb
class BusEvent < ApplicationRecord
  belongs_to :bus
  belongs_to :bus_stop
end

app/models/bus_service.rb
class BusService < ApplicationRecord
  belongs_to :service
  belongs_to :bus
  belongs_to :operator
end

app/models/bus_stop.rb
class BusStop < ApplicationRecord
end

app/models/bus_stop_congestion.rb
class BusStopCongestion < ApplicationRecord
  belongs_to :bus_stop
end

app/models/bus_stop_service.rb
class BusStopService < ApplicationRecord
  belongs_to :bus_stop
  belongs_to :service
end

app/models/device.rb
class Device < ApplicationRecord
  has_and_belongs_to_many :access_points
end

app/models/file_package.rb
class FilePackage < ApplicationRecord
  has_many :file_to_updates
  has_and_belongs_to_many :access_points
end

app/models/file_to_update.rb
class FileToUpdate < ApplicationRecord
  belongs_to :file_package
end

app/models/operator.rb
class Operator < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/subscribed_customer.rb
class SubscribedCustomer < ApplicationRecord
  belongs_to :access_group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/controllers/file_to_updates_controller.rb
class FileToUpdatesController < ApplicationController
  before_action :set_file_to_update, only: [:show, :edit, :update, :destroy]

  # GET /file_to_updates
  # GET /file_to_updates.json
  def index
    @file_to_updates = FileToUpdate.all
  end

  # GET /file_to_updates/1
  # GET /file_to_updates/1.json
  def show
  end

  # GET /file_to_updates/new
  def new
    @file_to_update = FileToUpdate.new
  end

  # GET /file_to_updates/1/edit
  def edit
  end

  # POST /file_to_updates
  # POST /file_to_updates.json
  def create
    @file_to_update = FileToUpdate.new(file_to_update_params)

    respond_to do |format|
      if @file_to_update.save
        format.html { redirect_to @file_to_update, notice: 'File to update was successfully created.' }
        format.json { render :show, status: :created, location: @file_to_update }
      else
        format.html { render :new }
        format.json { render json: @file_to_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_to_updates/1
  # PATCH/PUT /file_to_updates/1.json
  def update
    respond_to do |format|
      if @file_to_update.update(file_to_update_params)
        format.html { redirect_to @file_to_update, notice: 'File to update was successfully updated.' }
        format.json { render :show, status: :ok, location: @file_to_update }
      else
        format.html { render :edit }
        format.json { render json: @file_to_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_to_updates/1
  # DELETE /file_to_updates/1.json
  def destroy
    @file_to_update.destroy
    respond_to do |format|
      format.html { redirect_to file_to_updates_url, notice: 'File to update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_to_update
      @file_to_update = FileToUpdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def file_to_update_params
      params.require(:file_to_update).permit(:name, :file, :file_package_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_to_updates_helper.rb
module FileToUpdatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/file_to_updates/_form.html.erb
<%= form_with(model: file_to_update, local: true) do |form| %>
  <% if file_to_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(file_to_update.errors.count, "error") %> prohibited this file_to_update from being saved:</h2>

      <ul>
      <% file_to_update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.text_field :file %>
  </div>

  <div class="field">
    <%= form.label :file_package_id %>
    <%= form.number_field :file_package_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/file_to_updates/edit.html.erb
<h1>Editing File To Update</h1>

<%= render 'form', file_to_update: @file_to_update %>

<%= link_to 'Show', @file_to_update %> |
<%= link_to 'Back', file_to_updates_path %>

app/views/file_to_updates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>File To Updates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>File</th>
      <th>File package</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_to_updates.each do |file_to_update| %>
      <tr>
        <td><%= file_to_update.name %></td>
        <td><%= file_to_update.file %></td>
        <td><%= file_to_update.file_package_id %></td>
        <td><%= link_to 'Show', file_to_update %></td>
        <td><%= link_to 'Edit', edit_file_to_update_path(file_to_update) %></td>
        <td><%= link_to 'Destroy', file_to_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File To Update', new_file_to_update_path %>

app/views/file_to_updates/new.html.erb
<h1>New File To Update</h1>

<%= render 'form', file_to_update: @file_to_update %>

<%= link_to 'Back', file_to_updates_path %>

app/views/file_to_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @file_to_update.name %>
</p>

<p>
  <strong>File:</strong>
  <%= @file_to_update.file %>
</p>

<p>
  <strong>File package:</strong>
  <%= @file_to_update.file_package_id %>
</p>

<%= link_to 'Edit', edit_file_to_update_path(@file_to_update) %> |
<%= link_to 'Back', file_to_updates_path %>