config/routes.rb
Rails.application.routes.draw do
  mount API::Base, at: "/"
  devise_for :users
  resources :access_points
  resources :file_to_updates
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/access_group.rb
class AccessGroup < ApplicationRecord
end

app/models/access_group_service.rb
class AccessGroupService < ApplicationRecord
  belongs_to :access_group
  belongs_to :service
end

app/models/access_point.rb
class AccessPoint < ApplicationRecord
  has_and_belongs_to_many :devices
  has_and_belongs_to_many :file_packages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bus.rb
class Bus < ApplicationRecord
end

app/models/bus_event.rb
class BusEvent < ApplicationRecord
  belongs_to :bus
  belongs_to :bus_stop
end

app/models/bus_service.rb
class BusService < ApplicationRecord
  belongs_to :service
  belongs_to :bus
  belongs_to :operator
end

app/models/bus_stop.rb
class BusStop < ApplicationRecord
end

app/models/bus_stop_congestion.rb
class BusStopCongestion < ApplicationRecord
  belongs_to :bus_stop
end

app/models/bus_stop_service.rb
class BusStopService < ApplicationRecord
  belongs_to :bus_stop
  belongs_to :service
end

app/models/device.rb
class Device < ApplicationRecord
  has_and_belongs_to_many :access_points
end

app/models/file_package.rb
class FilePackage < ApplicationRecord
  has_many :file_to_updates
  has_and_belongs_to_many :access_points
end

app/models/file_to_update.rb
class FileToUpdate < ApplicationRecord
  belongs_to :file_package
end

app/models/operator.rb
class Operator < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/subscribed_customer.rb
class SubscribedCustomer < ApplicationRecord
  belongs_to :access_group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/controllers/access_points_controller.rb
class AccessPointsController < ApplicationController
  before_action :set_access_point, only: [:show, :edit, :update, :destroy]

  # GET /access_points
  # GET /access_points.json
  def index
    @access_points = AccessPoint.all
  end

  # GET /access_points/1
  # GET /access_points/1.json
  def show
  end

  # GET /access_points/new
  def new
    @access_point = AccessPoint.new
  end

  # GET /access_points/1/edit
  def edit
  end

  # POST /access_points
  # POST /access_points.json
  def create
    @access_point = AccessPoint.new(access_point_params)

    respond_to do |format|
      if @access_point.save
        format.html { redirect_to @access_point, notice: 'Access point was successfully created.' }
        format.json { render :show, status: :created, location: @access_point }
      else
        format.html { render :new }
        format.json { render json: @access_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /access_points/1
  # PATCH/PUT /access_points/1.json
  def update
    respond_to do |format|
      if @access_point.update(access_point_params)
        format.html { redirect_to @access_point, notice: 'Access point was successfully updated.' }
        format.json { render :show, status: :ok, location: @access_point }
      else
        format.html { render :edit }
        format.json { render json: @access_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /access_points/1
  # DELETE /access_points/1.json
  def destroy
    @access_points.file_packages
    access_point = AccessPoint.find(params[:id]).id
    FilePackage.access_points.delete(access_point)
    #@access_point.destroy
    respond_to do |format|
      format.html { redirect_to access_points_url, notice: 'Access point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_access_point
      @access_point = AccessPoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def access_point_params
      params.require(:access_point).permit(:mac, :ip, :status, :token, :last_message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/access_points_helper.rb
module AccessPointsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/access_points/_form.html.erb
<%= form_with(model: access_point, local: true) do |form| %>
  <% if access_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(access_point.errors.count, "error") %> prohibited this access_point from being saved:</h2>

      <ul>
      <% access_point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mac %>
    <%= form.text_field :mac %>
  </div>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token %>
  </div>

  <div class="field">
    <%= form.label :last_message %>
    <%= form.text_field :last_message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/access_points/edit.html.erb
<h1>Editing Access Point</h1>

<%= render 'form', access_point: @access_point %>

<%= link_to 'Show', @access_point %> |
<%= link_to 'Back', access_points_path %>

app/views/access_points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Access Points</h1>

<table>
  <thead>
    <tr>
      <th>Mac</th>
      <th>Ip</th>
      <th>Status</th>
      <th>Token</th>
      <th>Last message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @access_points.each do |access_point| %>
      <tr>
        <td><%= access_point.mac %></td>
        <td><%= access_point.ip %></td>
        <td><%= access_point.status %></td>
        <td><%= access_point.token %></td>
        <td><%= access_point.last_message %></td>
        <td><%= link_to 'Show', access_point %></td>
        <td><%= link_to 'Edit', edit_access_point_path(access_point) %></td>
        <td><%= link_to 'Destroy', access_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Access Point', new_access_point_path %>

app/views/access_points/new.html.erb
<h1>New Access Point</h1>

<%= render 'form', access_point: @access_point %>

<%= link_to 'Back', access_points_path %>

app/views/access_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mac:</strong>
  <%= @access_point.mac %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @access_point.ip %>
</p>

<p>
  <strong>Status:</strong>
  <%= @access_point.status %>
</p>

<p>
  <strong>Token:</strong>
  <%= @access_point.token %>
</p>

<p>
  <strong>Last message:</strong>
  <%= @access_point.last_message %>
</p>

<%= link_to 'Edit', edit_access_point_path(@access_point) %> |
<%= link_to 'Back', access_points_path %>